monitoring_grafana_admin_password: ENC[AES256_GCM,data:ZLaezZzFPWe7QXHs8/pqJ16lQwZ2B6uO,iv:Y6SnQcu9wwVo/Xhbfzjrv23L9TisJ/lWJrbsQpqiQJ4=,tag:4U2aCX8NwSoG/u1mf3hosw==,type:str]
monitoring_pve_token_value: ENC[AES256_GCM,data:y3ZLpdAg6g3wG2H7cEP/D8UE6n3uG8POj29ZUCzqLP23fY1Q,iv:RapzoT3FIvxEn5qCzzQPeyvkvW1TFNA47Z1mOmfI0uo=,tag:ZBasxv053exYrvxFQNFSYA==,type:str]
sops:
    age:
        - recipient: age1tv0xuwt0ys6adrjm2ad66dtzjc29jg4xcamuf8ceqmkulm3uvf8snx5jkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTGhCSFdpVlJTcXhXQlR3
            WWM4NkVQemsyQXpyVmpESDNUOERBYTlBNFNZCmJka0NxVlAxU2wrbVIxSDZLaUt0
            YXRsaThOUUc3SDhCbkwxWEV0T2RaYWMKLS0tIG9pUC94WDlMMXNlZnNpU3E4eXJ1
            M24xbkI4MVBMQkh3QVJRbEdLYTVxaUEKShs8NnWf3j5OoXqI6Wd1sAUqYaOPl3c2
            51JJ+uedU4GcIia+gFgaMLQ5eFAwEAF1kJrPxXoizlXugVWSCV7T4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-06T12:45:22Z"
    mac: ENC[AES256_GCM,data:DHRKLIncWo3xiU29H2eT19Iupcf1YmyEMKPg+foUAvE52+D0VW4FySRuImHvBp6rfXs/b63+BHnuP6w8GyOsja6oRWbekwUBTS3VmAUhZzkmxKULlNlLiC5B5Z8zPh55SUZh3Kx0jhCLEhndWtZQPkgK2nfQJ6rk7MX8PsznICM=,iv:T12sZ+NqcR51m//2OaMG1FEEXcpXTspTiqqL0EZw77U=,tag:bP23XYmhjBM+Zi/EaUnZug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
