---
caddy_otel_collector_host: 192.168.1.111
caddy_sites:
  - host: "monitoring.{{ lab_domain }}"
    upstream: "192.168.1.111:3000"
    health_path: /api/health
  - host: "auth.{{ lab_domain }}"
    upstream: "192.168.1.114:3000"
    health_path: /api/healthz
  - host: "filebrowser.{{ lab_domain }}"
    upstream: "192.168.1.115:8090"
    health_path: /health
