---
all:
  children:
    garage:
      hosts:
        garage.antoinejosset.fr:
          ansible_host: 192.168.1.112
    monitoring:
      hosts:
        monitoring.antoinejosset.fr:
          ansible_host: 192.168.1.111
