---
all:
  children:
    garage:
      hosts:
        garage.antoinejosset.fr:
          ansible_host: 192.168.1.112
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/jarvis_ed25519
          ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
