---
all:
  hosts:
    monitoring:
      ansible_host: 192.168.1.111
    garage:
      ansible_host: 192.168.1.112
    caddy:
      ansible_host: 192.168.1.113
    auth:
      ansible_host: 192.168.1.114
  children:
    docker_hosts:
      hosts:
        monitoring:
    observability:
      hosts:
        monitoring:
    garage_servers:
      hosts:
        garage:
    identity_servers:
      hosts:
        auth:
    reverse_proxies:
      hosts:
        caddy:
