name: exporters

services:
  node-exporter:
    restart: unless-stopped
    image: prom/node-exporter:v1.12.1
    pid: host
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "9100:9100"

  cadvisor:
    restart: unless-stopped
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    privileged: true
    command:
      - --docker_only=true
      - --housekeeping_interval=30s
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    ports:
      - "8080:8080"
